

/*INSERT INTO MOVIE VALUES(4, 'ID-400','movie-4');
INSERT INTO MOVIE VALUES(5, 'ID-500','movie-5');
INSERT INTO MOVIE VALUES(6, 'ID-600','movie-6');*/

/*SELECT * FROM TEST ORDER BY ID;
UPDATE TEST SET NAME='Hi' WHERE ID=1;
DELETE FROM TEST WHERE ID=2;*/