/*

DROP TABLE IF EXISTS MOVIE;

CREATE TABLE MOVIE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);*/

/*DROP TABLE IF EXISTS TEST;

CREATE TABLE MOVIE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MOVIE_ID VARCHAR(255),
    NAME VARCHAR(255)
);*/